spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mvc_rest
    username: mvc_user
    password: user1234
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
  sql:
    init:
      platform: mysql
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: database_create.sql